=== guigue/CRAAM-Instruments/SST/XMLtables/SSTDataDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:annotation>
        <xs:documentation xml:lang="en"> Generic Schema for SST Data Structures. Can be used with
            subintegration (RF, fast), integration (RS,slow) and auxiliary (BI, monitoring) raw data
            files. Every Data Structure xml file is constitued by a sequence of "SST Data Variables"
            which corresponds to a data variable (time, adc, temperature, etc) and contains the
            variable description: "name", "length" (1 if scalar, > 1 if array) and "type".
        </xs:documentation>
    </xs:annotation>
    <xs:element name="SSTDataFormat" type="SSTDataFormatType"/>
    <xs:complexType name="SSTDataFormatType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="SSTDataVariable" type="SSTDataVariableType"/>
        </xs:sequence>
        <xs:attribute name="DataType" type="xs:string"/>
        <xs:attribute name="InitialDate" type="xs:date"/>
        <xs:attribute name="FinalDate" type="xs:date"/>
        <xs:attribute name="IDLReference" type="xs:string"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="SSTDataVariableType">
        <xs:sequence>
            <xs:element name="VarName" type="xs:string"/>
            <xs:element name="VarLength" type="xs:integer"/>
            <xs:element name="VarType" type="xs:string"/>
            <xs:element name="VarUnit" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="VarName" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== guigue/CRAAM-Instruments/SST/XMLtables/AuxiliaryDataFormat-1900-01-01_to_2002-09-15.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="SSTDataDescription.xsd" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>

<!--     
                       SST Data Description. 

Type      = Auxiliary (BI, monitoring)
Time Span = 1900-01-01 to 2002-09-15
Origin    = IDL sst_struct.pro, version 2017-07-29, lines: 105-117
Structure = (from IDL)

        nradiom = 6
        nchan   = 8

        raw_struc = {n_struc                      , $
                     time:         0l             , $
                     azipos:       0.0            , $ 
                     elepos:       0.0            , $ 
                     azierr:       0.0            , $ 
                     eleerr:       0.0            , $
                     adc:          intarr(nchan)  , $ 
                     sigma:        fltarr(nchan)  , $ 
                     gps_status:   0              , $ 
                     daq_status:   0              , $ 
                     acq_gain:     0              , $
                     target:       0b             , $ 
                     opmode:       0b             , $
                     att:          intarr(nradiom), $
                     off:          intarr(nradiom), $
                     mix_volt:     fltarr(nradiom), $
                     mix_curr:     fltarr(nradiom), $
                     hot_temp:     0.0            , $ 
                     amb_temp:     0.0            , $
                     opt_temp:     0.0            , $
                     if_board_temp:0.0            , $
                     radome_temp:  0.0            , $
                     humidity:     0.0            , $
                     wind:         0.0            , $
                     opac_210:     0.0            , $
                     opac_405:     0.0            , $
                     elevation:    0.0            , $ 
                     seeing:       0.0            , $
                     burst :       0b             , $
                     errors:       0l             }
            
-->

<SSTDataFormat 
    DataType="Auxiliary" 
    InitialDate="1900-01-01" 
    FinalDate="2002-09-15"
    IDLReference="sst_struc.pro:105-117"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="SSTDataDescription.xsd">

    <SSTDataVariable VarName="time">
        <VarName>time</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>Hus</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="azipos">
        <VarName>azipos</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>Deg</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="elepos">
        <VarName>elepos</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>Deg</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="azierr">
        <VarName>azierr</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>Deg</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="eleerr">
        <VarName>eleerr</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>Deg</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="adc">
        <VarName>adc</VarName>
        <VarLength>8</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>ADCu</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="sigma">
        <VarName>sigma</VarName>
        <VarLength>8</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>ADCu</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="gps_status">
        <VarName>gps_status</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="daq_status">
        <VarName>daq_status</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="acq_gain">
        <VarName>acq_gain</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="target">
        <VarName>target</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:byte</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="opmode">
        <VarName>opmode</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:byte</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="att">
        <VarName>att</VarName>
        <VarLength>6</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>dB</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="off">
        <VarName>off</VarName>
        <VarLength>6</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>ADCu</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="mix_volt">
        <VarName>mix_volt</VarName>
        <VarLength>6</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>mV</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="mix_curr">
        <VarName>mix_curr</VarName>
        <VarLength>6</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>mA</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="hot_temp">
        <VarName>hot_temp</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>C</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="amb_temp">
        <VarName>amb_temp</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>C</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="opt_temp">
        <VarName>opt_temp</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>C</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="if_board">
        <VarName>if_board</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>C</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="radome_temp">
        <VarName>radome_temp</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>C</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="humidity">
        <VarName>humidity</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>%</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="wind">
        <VarName>wind</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="opac_210">
        <VarName>opac_210</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="opac_405">
        <VarName>opac_405</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="elevation">
        <VarName>elevation</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="seeing">
        <VarName>seeing</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="burst">
        <VarName>burst</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:byte</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="errors">
        <VarName>errors</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>

</SSTDataFormat>

=== guigue/CRAAM-Instruments/SstModulesTccRafaelFrederico/XML_TABLES/DataFormat-2002-12-14_to_2100-01-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="SSTDataDescription.xsd" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>

<!-- 
    
                       SST Data Description. 

Type      = SubIntegration (RF,fast) and Integration (RS, integrated)
Time Span = 2002-12-14 to 2100-01-01
Origin    = IDL sst_struct.pro, version 2017-07-29, lines 175-183
Structure = (from IDL)

            nradiom = 6
            nchan   = 6
            raw_struc={n_struc,                   $
                       time:      0l,             $
                       adcval:    uintarr(nchan), $
                       pos_time:  0l,             $
                       azipos:    0l,             $
                       elepos:    0l,             $
                       pm_daz:    0,              $
                       pm_del:    0,              $
                       azierr:    0l,             $
                       eleerr:    0l,             $
                       x_off:     0,              $
                       y_off:     0,              $
                       off:       intarr(nradiom),$
                       target:    0b,             $
                       opmode:    0b,             $
                       gps_status:0,              $
                       recnum:    0l              }

Author = Guigue
Date   = 2017-07-29

-->

<SSTDataFormat 
    DataType="Data" 
    InitialDate="2002-12-14" 
    FinalDate="2100-01-01" 
    IDLReference="sst_struc.pro:175-183"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="SSTDataDescription.xsd">
    
    <SSTDataVariable VarName="time">
        <VarName>time</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>Hus</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="adcval">
        <VarName>adcval</VarName>
        <VarLength>6</VarLength>
        <VarType>xs:unsignedShort</VarType>
        <VarUnit>ADCu</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="pos_time">
        <VarName>pos_time</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>Hus</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="azipos">
        <VarName>azipos</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="elepos">
        <VarName>elepos</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>

    <SSTDataVariable VarName="pm_daz">
        <VarName>pm_daz</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="pm_del">
        <VarName>pm_del</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="azierr">
        <VarName>azierr</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="eleerr">
        <VarName>eleerr</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="x_off">
        <VarName>x_off</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="y_off">
        <VarName>y_off</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="off">
        <VarName>off</VarName>
        <VarLength>6</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>ADCu</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="target">
        <VarName>target</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:byte</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="opmode">
        <VarName>opmode</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:byte</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="gps_status">
        <VarName>gps_status</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="recnum">
        <VarName>recnum</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
</SSTDataFormat>

=== guigue/CRAAM-Instruments/SST/XMLtables/DataFormat-1900-01-01_to_1999-05-01.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-model href="SSTDataDescription.xsd" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>

<!--     
                       SST Data Description. 

Type      = SubIntegration (RF,fast) and Integration (RS, integrated)
Time Span = 1900-01-01 to 1999-05-01
Origin    = IDL sst_struct.pro, version 2017-07-29, lines: 216-224
Structure = (from IDL)

            nradiom = 6
            nchan   = 8
            raw_struc={n_struc,
                       time:0l, 
                       adcval:     intarr(nchan)   ,$ 
                       pos_time:   0l              ,$
                       azipos:     0l              ,$ 
                       elepos:     0l              ,$ 
                       azivel:     0               ,$ 
                       elevel:     0               ,$ 
                       azierr:     0l              ,$
                       eleerr:     0l              ,$ 
                       att:        intarr(nradiom) ,$
                       target:     0b              ,$ 
                       opmode:     0b              ,$ 
                       gps_status: 0               ,$ 
                       daq_status: 0               ,$ 
                       recnum:     0l              }
      
-->

<SSTDataFormat 
    DataType="Data"
    InitialDate="1900-01-01"
    FinalDate="1999-05-01"
    IDLReference="sst_struc.pro:216-224"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="SSTDataDescription.xsd">
    
    <SSTDataVariable VarName="time">
        <VarName>time</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>Hus</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="adcval">
        <VarName>adcval</VarName>
        <VarLength>8</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>ADCu</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="pos_time">
        <VarName>pos_time</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>Hus</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="azipos">
        <VarName>azipos</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="elepos">
        <VarName>elepos</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="azivel">
        <VarName>azivel</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>mDeg/s</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="elevel">
        <VarName>elevel</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>mDeg/s</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="azierr">
        <VarName>azierr</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="eleerr">
        <VarName>eleerr</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>mDeg</VarUnit>
    </SSTDataVariable>
        
    <SSTDataVariable VarName="att">
        <VarName>att</VarName>
        <VarLength>6</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>dB</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="target">
        <VarName>target</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:byte</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="opmode">
        <VarName>opmode</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:byte</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="gps_status">
        <VarName>gps_status</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="daq_status">
        <VarName>daq_status</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:short</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
    <SSTDataVariable VarName="recnum">
        <VarName>recnum</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
    </SSTDataVariable>
    
</SSTDataFormat>
