=== guigue/CRAAM-Instruments/POEMAS/XMLTables/POEMASDataDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="POEMASDataFormat" type="POEMASDataFormatType"/>
    <xs:complexType name="POEMASDataFormatType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="POEMASDataVariable" type="POEMASDataVariableType"/>
        </xs:sequence>
        <xs:attribute name="DataType" type="xs:string"/>
        <xs:attribute name="InitialDate" type="xs:date"/>
    </xs:complexType>
    <xs:complexType name="POEMASDataVariableType">
        <xs:sequence>
            <xs:element name="VarName" type="xs:string"/>
            <xs:element name="VarLength" type="xs:integer"/>
            <xs:element name="VarType" type="xs:string"/>
            <xs:element name="VarUnit" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="VarName" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== guigue/CRAAM-Instruments/POEMAS/XMLTables/POEMASIntegrationDataFormat.xml
<?xml version="1.0" encoding="UTF-8"?>

<POEMASDataFormat
    DataType="Data" 
    InitialDate="2001-1-1" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="POEMASDataDescription.xsd">

    <POEMASDataVariable VarName="sec">
        <VarName>sec</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="ele_ang">
        <VarName>ele_ang</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="azi_ang">
        <VarName>zi_ang</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>


    <POEMASDataVariable VarName="mTBL_45">
        <VarName>mTBL_45</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="mTBR_45">
        <VarName>mTBR_45</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="mTBL_90">
        <VarName>mTBL_90</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="mTBR_90">
        <VarName>mTBR_90</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>


    <POEMASDataVariable VarName="sTBL_45">
        <VarName>sTBL_45</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="sTBR_45">
        <VarName>sTBR_45</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="sTBL_90">
        <VarName>sTBL_90</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="sTBR_90">
        <VarName>sTBR_90</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

</POEMASDataFormat>

=== guigue/CRAAM-Instruments/POEMAS/XMLTables/POEMASDataFormat.xml
<?xml version="1.0" encoding="UTF-8"?>

<POEMASDataFormat
    DataType="Data" 
    InitialDate="2001-1-1" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="POEMASDataDescription.xsd">

    <POEMASDataVariable VarName="sec">
        <VarName>sec</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="ele_ang">
        <VarName>ele_ang</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="azi_ang">
        <VarName>zi_ang</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="TB">
        <VarName>TB</VarName>
        <VarLength>400</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>


</POEMASDataFormat>

=== guigue/CRAAM-Instruments/POEMAS/XMLTables/POEMASDataFormatHead.xml
<?xml version="1.0" encoding="UTF-8"?>

<POEMASDataFormat
    DataType="Data" 
    InitialDate="2001-1-1" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="POEMASDataDescription.xsd">

    <POEMASDataVariable VarName="Code">
        <VarName>Code</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="NRS">
        <VarName>NRS</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="FreqNo">
        <VarName>FreqNo</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>GHz</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="Freq1">
        <VarName>Freq1</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>GHz</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="Freq2">
        <VarName>Freq2</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>GHz</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="BRTMin">
        <VarName>BRTMin</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

    <POEMASDataVariable VarName="BRTMax">
        <VarName>BRTMAX</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:float</VarType>
        <VarUnit>none</VarUnit>
    </POEMASDataVariable>

</POEMASDataFormat>
