=== guigue/CRAAM-Instruments/HATS/XMLTables/HATSAuxDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="HATSAuxFormat" type="HATSAuxFormatType"/>
    <xs:complexType name="HATSAuxFormatType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="HATSAuxVariable" type="HATSAuxVariableType"/>
        </xs:sequence>
        <xs:attribute name="DataType" type="xs:string"/>
        <xs:attribute name="InitialDate" type="xs:date"/>
        <xs:attribute name="FinalDate" type="xs:date"/>
    </xs:complexType>
    <xs:complexType name="HATSAuxVariableType">
        <xs:sequence>
            <xs:element name="VarName" type="xs:string"/>
            <xs:element name="VarLength" type="xs:integer"/>
            <xs:element name="VarType" type="xs:string"/>
            <xs:element name="VarUnit" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== guigue/CRAAM-Instruments/HATS/XMLTables/HATSAuxFormat.xml
<?xml version="1.0" encoding="UTF-8"?>

<HATSAuxFormat
    DataType="Data" 
    InitialDate="2021-10-25" 
    FinalDate="2100-01-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="HATSAuxDescription.xsd">
    
    <HATSAuxVariable VarName="Timestamp_husec">
        <VarName>husec</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:unsignedLong</VarType>
        <VarUnit>none</VarUnit>
    </HATSAuxVariable>
    
    <HATSAuxVariable VarName="Timestamp_JD">
        <VarName>jd</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:double</VarType>
        <VarUnit>day</VarUnit>
    </HATSAuxVariable>
    
    <HATSAuxVariable VarName="Timestamp_Sid">
        <VarName>sid</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:double</VarType>
        <VarUnit>hour</VarUnit>
    </HATSAuxVariable>
    
    <HATSAuxVariable VarName="Pos_Alt">
        <VarName>elevation</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:double</VarType>
        <VarUnit>degrees</VarUnit>
    </HATSAuxVariable>
    
    <HATSAuxVariable VarName="Pos_Az">
        <VarName>azimuth</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:double</VarType>
        <VarUnit>degrees</VarUnit>
    </HATSAuxVariable>
    
        <HATSAuxVariable VarName="Pos_RA">
        <VarName>right_ascension</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:double</VarType>
        <VarUnit>degrees</VarUnit>
    </HATSAuxVariable>

    <HATSAuxVariable VarName="Pos_Dec">
        <VarName>declination</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:double</VarType>
        <VarUnit>degrees</VarUnit>
    </HATSAuxVariable>
    
    <HATSAuxVariable VarName="Rate_RA">
        <VarName>ra_rate</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:double</VarType>
        <VarUnit>degrees/s</VarUnit>
    </HATSAuxVariable>
    
    <HATSAuxVariable VarName="Rate_Dec">
        <VarName>dec_rate</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:double</VarType>
        <VarUnit>degrees/s</VarUnit>
    </HATSAuxVariable>
    
    <HATSAuxVariable VarName="Object">
        <VarName>object</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>degrees/s</VarUnit>
    </HATSAuxVariable>
    
    <HATSAuxVariable VarName="Opmode">
        <VarName>opmode</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>degrees/s</VarUnit>
    </HATSAuxVariable>
    
  </HATSAuxFormat>
