=== guigue/CRAAM-Instruments/HATS/XMLTables/HATSDataDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="HATSDataFormat" type="HATSDataFormatType"/>
    <xs:complexType name="HATSDataFormatType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="HATSDataVariable" type="HATSDataVariableType"/>
        </xs:sequence>
        <xs:attribute name="DataType" type="xs:string"/>
        <xs:attribute name="InitialDate" type="xs:date"/>
        <xs:attribute name="FinalDate" type="xs:date"/>
    </xs:complexType>
    <xs:complexType name="HATSDataVariableType">
        <xs:sequence>
            <xs:element name="VarName" type="xs:string"/>
            <xs:element name="VarLength" type="xs:integer"/>
            <xs:element name="VarType" type="xs:string"/>
            <xs:element name="VarUnit" type="xs:string"/>
            <xs:element name="VarOrigin" type="xs:string"/>
            <xs:element name="Convert" type="xs:string"/>
            <xs:element name="ConvOrd" type="xs:float"/>
            <xs:element name="ConvSlope" type="xs:float"/>
        </xs:sequence>
        <xs:attribute name="VarName" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== guigue/CRAAM-Instruments/HATS/XMLTables/HATSDataFormat-110.xml
<?xml version="1.0" encoding="UTF-8"?>

<HATSDataFormat
    DataType="Data" 
    InitialDate="2021-08-01" 
    FinaelDate="2021-10-25"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="HATSDataDescription.xsd">

    <HATSDataVariable VarName="Sample">
        <VarName>sample</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:unsignedInt</VarType>
        <VarUnit>none</VarUnit>
    </HATSDataVariable>

    <HATSDataVariable VarName="Timestamp_sec">
        <VarName>sec</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:unsignedInt</VarType>
        <VarUnit>none</VarUnit>
    </HATSDataVariable>

    <HATSDataVariable VarName="Timestamp_ms">
        <VarName>ms</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:unsignedShort</VarType>
        <VarUnit>none</VarUnit>
    </HATSDataVariable>

    <HATSDataVariable VarName="husec">
        <VarName>husec</VarName>
                <VarLength>1</VarLength>
        <VarType>xs:unsignedLong</VarType>
        <VarUnit>none</VarUnit>
    </HATSDataVariable>

<HATSDataVariable VarName="rawGolay">
        <VarName>adcu</VarName>
                <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
    </HATSDataVariable>

<HATSDataVariable VarName="rawPS">
        <VarName>chopper</VarName>
                <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
    </HATSDataVariable>


</HATSDataFormat>

=== guigue/CRAAM-Instruments/HATS/XMLTables/HATSDataFormat-120.xml
<?xml version="1.0" encoding="UTF-8"?>

<HATSDataFormat
    DataType="Data" 
    InitialDate="2021-10-25" 
    FinalDate="2100-01-01"
    FFTProgram="/monalisa/guigue/Programming/CRAAM-Instruments/HATS/HATS_fft"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="HATSDataDescription.xsd">

    <HATSDataVariable VarName="Sample">
        <VarName>sample</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:unsignedInt</VarType>
        <VarUnit>none</VarUnit>
        <VarOrigin>sam4e</VarOrigin>
        <Convert>no</Convert>
        <ConvOrd>0.0</ConvOrd>
        <ConvSlope>1.0</ConvSlope>
    </HATSDataVariable>

    <HATSDataVariable VarName="Timestamp_sec">
        <VarName>sec</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:unsignedInt</VarType>
        <VarUnit>none</VarUnit>
        <VarOrigin>sam4e</VarOrigin>
        <Convert>no</Convert>
        <ConvOrd>0.0</ConvOrd>
        <ConvSlope>1.0</ConvSlope>
    </HATSDataVariable>

    <HATSDataVariable VarName="Timestamp_ms">
        <VarName>ms</VarName>
        <VarLength>1</VarLength>
        <VarType>xs:unsignedShort</VarType>
        <VarUnit>none</VarUnit>
        <VarOrigin>sam4e</VarOrigin>
        <Convert>no</Convert>
        <ConvOrd>0.0</ConvOrd>
        <ConvSlope>1.0</ConvSlope>
    </HATSDataVariable>

    <HATSDataVariable VarName="Timestamp_husec">
        <VarName>husec</VarName>
                <VarLength>1</VarLength>
        <VarType>xs:unsignedLong</VarType>
        <VarUnit>none</VarUnit>
        <VarOrigin>sam4e</VarOrigin>
        <Convert>no</Convert>
        <ConvOrd>0.0</ConvOrd>
        <ConvSlope>1.0</ConvSlope>
    </HATSDataVariable>

<HATSDataVariable VarName="rawGolay">
        <VarName>golay</VarName>
                <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
        <VarOrigin>ad7770</VarOrigin>
        <Convert>yes</Convert>
        <ConvOrd>-6.987</ConvOrd>
        <ConvSlope>0.005808</ConvSlope>
    </HATSDataVariable>

<HATSDataVariable VarName="rawChopper">
        <VarName>chopper</VarName>
                <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
        <VarOrigin>ad7770</VarOrigin>
        <Convert>yes</Convert>
        <ConvOrd>0.13110863205497668</ConvOrd>
        <ConvSlope>0.00029855314482167888</ConvSlope>
    </HATSDataVariable>
    
<HATSDataVariable VarName="rawTemp_HICS">
        <VarName>temp_hics</VarName>
                <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
        <VarOrigin>ad7770</VarOrigin>
        <Convert>yes</Convert>
        <ConvOrd>0.013110863205497668</ConvOrd>
        <ConvSlope>0.000029855314482167888</ConvSlope>
    </HATSDataVariable>

<HATSDataVariable VarName="rawTemp_ENV">
        <VarName>temp_env</VarName>
                <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
        <VarOrigin>ad7770</VarOrigin>
        <Convert>yes</Convert>
        <ConvOrd>0.013110863205497668</ConvOrd>
        <ConvSlope>0.000029855314482167888</ConvSlope>
    </HATSDataVariable>

<HATSDataVariable VarName="rawTemp_GOLAY">
        <VarName>temp_golay</VarName>
                <VarLength>1</VarLength>
        <VarType>xs:int</VarType>
        <VarUnit>none</VarUnit>
        <VarOrigin>ad7770</VarOrigin>
        <Convert>yes</Convert>
        <ConvOrd>0.013110863205497668</ConvOrd>
        <ConvSlope>0.000029855314482167888</ConvSlope>
    </HATSDataVariable>

</HATSDataFormat>
